import React, { useState, useEffect } from 'react';
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalCloseButton,
  ModalFooter,
  Button,
  VStack,
  Box,
  Text,
  Input,
  Textarea,
  useToast,
  Spinner,
  Flex,
  IconButton,
  Tooltip,
} from '@chakra-ui/react';
import { EditIcon, DownloadIcon, CheckIcon, CloseIcon } from '@chakra-ui/icons';
import { useSelector } from 'react-redux';
import { selectUser } from '../../store/slices/authSlice';

const NotesModal = ({
  isOpen,
  onClose,
  channelId,
  threadId = null,
  channelName,
  threadTitle = null,
}) => {
  const [notes, setNotes] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedNotes, setEditedNotes] = useState(null);
  const toast = useToast();
  const currentUser = useSelector(selectUser);

  useEffect(() => {
    if (isOpen) {
      generateNotes();
    }
  }, [isOpen, channelId, threadId]);

  const generateNotes = async () => {
    try {
      setIsLoading(true);
      const token = localStorage.getItem('token');
      
      const response = await fetch(
        `${import.meta.env.VITE_API_URL || 'http://localhost:5001'}/api/ai/generate-notes?` + 
        new URLSearchParams({
          channel_id: channelId,
          ...(threadId && { thread_id: threadId }),
        }),
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          credentials: 'include',
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to generate notes');
      }

      const { status, data, error } = await response.json();
      
      if (status === 'error' || error) {
        throw new Error(error || 'Failed to generate notes');
      }
      
      setNotes(data);
      setEditedNotes(data); // Initialize edited notes with generated notes
    } catch (error) {
      console.error('Error generating notes:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to generate notes',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async () => {
    try {
      const token = localStorage.getItem('token');
      
      const response = await fetch(
        `${import.meta.env.VITE_API_URL || 'http://localhost:5001'}/api/notes/${notes.id}`,
        {
          method: 'PUT',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(editedNotes),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to save notes');
      }

      const { status, data, error } = await response.json();
      
      if (status === 'error' || error) {
        throw new Error(error || 'Failed to save notes');
      }
      
      setNotes(data);
      setEditedNotes(data);
      setIsEditing(false);
      
      toast({
        title: 'Success',
        description: 'Notes saved successfully',
        status: 'success',
        duration: 2000,
        isClosable: true,
      });
    } catch (error) {
      console.error('Error saving notes:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to save notes',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
    }
  };

  const handleExport = () => {
    try {
      // Create markdown content
      let markdown = `# ${notes.title}\n\n`;
      markdown += `Generated from ${threadId ? 'thread' : 'channel'}: ${channelName}\n`;
      if (threadTitle) {
        markdown += `Thread: ${threadTitle}\n`;
      }
      markdown += `Generated by: ${currentUser.username}\n`;
      markdown += `Date: ${new Date().toLocaleString()}\n\n`;

      notes.sections.forEach(section => {
        markdown += `## ${section.title}\n\n`;
        section.content.forEach(item => {
          markdown += `* ${item}\n`;
        });
        markdown += '\n';
      });

      // Create and download file
      const blob = new Blob([markdown], { type: 'text/markdown' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${notes.title.toLowerCase().replace(/\s+/g, '-')}.md`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      toast({
        title: 'Success',
        description: 'Notes exported successfully',
        status: 'success',
        duration: 2000,
        isClosable: true,
      });
    } catch (error) {
      console.error('Error exporting notes:', error);
      toast({
        title: 'Error',
        description: 'Failed to export notes',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="xl">
      <ModalOverlay />
      <ModalContent bg="gray.800" color="white">
        <ModalHeader>
          <Flex justify="space-between" align="center">
            <Text>Meeting Notes</Text>
            <Flex gap={2}>
              {notes && !isEditing && (
                <>
                  <Tooltip label="Edit Notes">
                    <IconButton
                      icon={<EditIcon />}
                      onClick={() => setIsEditing(true)}
                      size="sm"
                      colorScheme="blue"
                    />
                  </Tooltip>
                  <Tooltip label="Export as Markdown">
                    <IconButton
                      icon={<DownloadIcon />}
                      onClick={handleExport}
                      size="sm"
                      colorScheme="green"
                    />
                  </Tooltip>
                </>
              )}
              {isEditing && (
                <>
                  <Tooltip label="Save Changes">
                    <IconButton
                      icon={<CheckIcon />}
                      onClick={handleSave}
                      size="sm"
                      colorScheme="green"
                    />
                  </Tooltip>
                  <Tooltip label="Cancel Editing">
                    <IconButton
                      icon={<CloseIcon />}
                      onClick={() => {
                        setIsEditing(false);
                        setEditedNotes(notes);
                      }}
                      size="sm"
                      colorScheme="red"
                    />
                  </Tooltip>
                </>
              )}
            </Flex>
          </Flex>
        </ModalHeader>
        <ModalCloseButton />
        
        <ModalBody>
          {isLoading ? (
            <Flex justify="center" align="center" minH="300px">
              <Spinner size="xl" color="blue.500" />
            </Flex>
          ) : notes ? (
            <VStack spacing={6} align="stretch">
              {isEditing ? (
                // Edit Mode
                <>
                  <Input
                    value={editedNotes.title}
                    onChange={(e) => setEditedNotes({
                      ...editedNotes,
                      title: e.target.value
                    })}
                    fontWeight="bold"
                    size="lg"
                    bg="gray.700"
                  />
                  {editedNotes.sections.map((section, sectionIndex) => (
                    <Box key={sectionIndex}>
                      <Input
                        value={section.title}
                        onChange={(e) => {
                          const newSections = [...editedNotes.sections];
                          newSections[sectionIndex].title = e.target.value;
                          setEditedNotes({
                            ...editedNotes,
                            sections: newSections
                          });
                        }}
                        fontWeight="semibold"
                        mb={2}
                        bg="gray.700"
                      />
                      <VStack spacing={2} align="stretch">
                        {section.content.map((item, itemIndex) => (
                          <Textarea
                            key={itemIndex}
                            value={item}
                            onChange={(e) => {
                              const newSections = [...editedNotes.sections];
                              newSections[sectionIndex].content[itemIndex] = e.target.value;
                              setEditedNotes({
                                ...editedNotes,
                                sections: newSections
                              });
                            }}
                            size="sm"
                            bg="gray.700"
                          />
                        ))}
                      </VStack>
                    </Box>
                  ))}
                </>
              ) : (
                // View Mode
                <>
                  <Text fontSize="2xl" fontWeight="bold">
                    {notes.title}
                  </Text>
                  {notes.sections.map((section, index) => (
                    <Box key={index}>
                      <Text fontSize="xl" fontWeight="semibold" mb={2}>
                        {section.title}
                      </Text>
                      <VStack spacing={2} align="stretch" pl={4}>
                        {section.content.map((item, itemIndex) => (
                          <Text key={itemIndex}>• {item}</Text>
                        ))}
                      </VStack>
                    </Box>
                  ))}
                </>
              )}
            </VStack>
          ) : (
            <Text color="gray.400" textAlign="center">
              No notes generated yet
            </Text>
          )}
        </ModalBody>

        <ModalFooter>
          <Button colorScheme="blue" mr={3} onClick={onClose}>
            Close
          </Button>
          {notes && !isLoading && (
            <Button
              colorScheme="green"
              onClick={generateNotes}
              leftIcon={<Spinner size="sm" />}
            >
              Regenerate
            </Button>
          )}
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};

export default NotesModal; 